/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as JoinRouteImport } from './routes/join'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as PlayersStatsRouteImport } from './routes/players/stats'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersStatsRoute = PlayersStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => PlayersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/join': typeof JoinRoute
  '/meetings': typeof MeetingsRoute
  '/players': typeof PlayersRouteWithChildren
  '/players/stats': typeof PlayersStatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/join': typeof JoinRoute
  '/meetings': typeof MeetingsRoute
  '/players': typeof PlayersRouteWithChildren
  '/players/stats': typeof PlayersStatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/join': typeof JoinRoute
  '/meetings': typeof MeetingsRoute
  '/players': typeof PlayersRouteWithChildren
  '/players/stats': typeof PlayersStatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/about' | '/join' | '/meetings' | '/players' | '/players/stats'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/join' | '/meetings' | '/players' | '/players/stats'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/join'
    | '/meetings'
    | '/players'
    | '/players/stats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  JoinRoute: typeof JoinRoute
  MeetingsRoute: typeof MeetingsRoute
  PlayersRoute: typeof PlayersRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/stats': {
      id: '/players/stats'
      path: '/stats'
      fullPath: '/players/stats'
      preLoaderRoute: typeof PlayersStatsRouteImport
      parentRoute: typeof PlayersRoute
    }
  }
}

interface PlayersRouteChildren {
  PlayersStatsRoute: typeof PlayersStatsRoute
}

const PlayersRouteChildren: PlayersRouteChildren = {
  PlayersStatsRoute: PlayersStatsRoute,
}

const PlayersRouteWithChildren =
  PlayersRoute._addFileChildren(PlayersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  JoinRoute: JoinRoute,
  MeetingsRoute: MeetingsRoute,
  PlayersRoute: PlayersRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
